name: Jekyll site CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    name: test
    runs-on: [self-hosted, linux, t2-micro]
    steps:
      - run: echo $GITHUB_WORKSPACE
      - run: echo $USER
